services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'

    # Authenticator personnalisé (ex: JwtCookieAuthenticator)
    App\Security\JwtCookieAuthenticator: ~

    # Handler personnalisé à la connexion : génère le token et le met dans un cookie,
    # + personnalise le payload JWT via event subscriber
    App\Security\JWTAuthenticationSuccessHandler:
        arguments:
            $cookieName: 'BEARER'
            $cookieLifetime: 3600
            $cookieSecure: '%env(bool:APP_COOKIE_SECURE)%'  # définir dans .env (false en dev)
            $cookieSameSite: 'Lax'
        tags:
            - { name: kernel.event_subscriber }

    # LogoutHandler pour supprimer le cookie au logout (optionnel)
    App\Security\LogoutHandler:
        tags:
            - { name: 'kernel.event_listener', event: 'Symfony\Component\Security\Http\Event\LogoutEvent', method: 'onLogout' }
