nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^https?://localhost(:[0-9]+)?$', '^https?://127.0.0.1(:[0-9]+)?$']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        allow_credentials: true
        max_age: 3600

    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['^https?://localhost(:[0-9]+)?$', '^https?://127.0.0.1(:[0-9]+)?$']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_credentials: true
            max_age: 3600

        '^/login':
            origin_regex: true
            allow_origin: ['^https?://localhost(:[0-9]+)?$', '^https?://127.0.0.1(:[0-9]+)?$']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'OPTIONS']
            allow_credentials: true
            max_age: 3600
