vich_uploader:
    db_driver: orm
    storage: file_system
    mappings:
        product_images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
