controllers:
    resource:
        path: ../src/Controller/Public
        namespace: App\Controller\Public
    type: attribute

admin_controllers:
    resource:
        path: ../src/Controller/BackOffice/
        namespace: App\Controller\Admin
    prefix: 'admin'
    type: attribute